### ISSUE TITLE
Dynamic Shard Data

### ISSUE THREAD

**Issue by TheHolyWaffle** [loldevs/riotapi#18]
Because Riot sometimes changes hostnames of its services (rarely, but it happens) it might be a good idea to load the shard data dynamically. 

---

This can be done by issuing a GET request to the latest `lol.properties` depending on the region to the following url: `http://l3cdn.riotgames.com/releases/live/projects/lol_air_client_config_<regionTag>/releases/<releaseVersion>/files/lol.properties`

For example: http://l3cdn.riotgames.com/releases/live/projects/lol_air_client_config_euw/releases/0.0.0.48/files/lol.properties

---

The `releaseVersion` is independent from each region and can be found through the following url: `http://l3cdn.riotgames.com/releases/live/projects/lol_air_client_config_<regionTag>/releases/releaselisting_<REGIONTAG>`

For example: http://l3cdn.riotgames.com/releases/live/projects/lol_air_client_config_euw/releases/releaselisting_EUW

or

http://l3cdn.riotgames.com/releases/live/projects/lol_air_client_config_oc1/releases/releaselisting_OC1

notice: the capitalization is important

**Comment by chienhao10** [comment]
http://l3cdn.riotgames.com/releases/pbe/projects/lol_air_client_config/releases/0.0.0.37/files/lol.properties
I think this file can be use to switching server by using NA client if we replace the info in there with PBE one. so NA client will connect to PBE instead of NA. But it will keep change back to NA even i have it read-only. have any idea use NA client connect to PBE, so dont have to download 2 different clients?
